# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/teacher_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.teacher_mode = QtWidgets.QWidget(self.centralwidget)
        self.teacher_mode.setStyleSheet("#teacher_mode{\n"
"background-color:#FCFAED;\n"
"}")
        self.teacher_mode.setObjectName("teacher_mode")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.teacher_mode)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu = QtWidgets.QWidget(self.teacher_mode)
        self.menu.setMinimumSize(QtCore.QSize(0, 60))
        self.menu.setMaximumSize(QtCore.QSize(16777215, 60))
        self.menu.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"\n"
"#menu{\n"
"background-color:#FFCD00;\n"
"\n"
"}\n"
"\n"
"QToolButton{\n"
"border:none;\n"
"}\n"
"\n"
"QLineEdit{\n"
"border:none;\n"
"border-radius:5px;\n"
"}")
        self.menu.setObjectName("menu")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.menu)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menu_1_open = QtWidgets.QWidget(self.menu)
        self.menu_1_open.setMinimumSize(QtCore.QSize(150, 0))
        self.menu_1_open.setMaximumSize(QtCore.QSize(200, 16777215))
        self.menu_1_open.setObjectName("menu_1_open")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.menu_1_open)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.open_menu_button = QtWidgets.QPushButton(self.menu_1_open)
        self.open_menu_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/ui\\icon/menu_bar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_menu_button.setIcon(icon)
        self.open_menu_button.setIconSize(QtCore.QSize(50, 50))
        self.open_menu_button.setCheckable(True)
        self.open_menu_button.setAutoExclusive(True)
        self.open_menu_button.setObjectName("open_menu_button")
        self.horizontalLayout_4.addWidget(self.open_menu_button)
        self.teacher_txt = QtWidgets.QLabel(self.menu_1_open)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.teacher_txt.setFont(font)
        self.teacher_txt.setObjectName("teacher_txt")
        self.horizontalLayout_4.addWidget(self.teacher_txt)
        self.horizontalLayout_3.addWidget(self.menu_1_open)
        self.menu_2 = QtWidgets.QWidget(self.menu)
        self.menu_2.setObjectName("menu_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.menu_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.menu_2)
        self.menu_3 = QtWidgets.QWidget(self.menu)
        self.menu_3.setMinimumSize(QtCore.QSize(150, 0))
        self.menu_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_3.setStyleSheet("")
        self.menu_3.setObjectName("menu_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.menu_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.min_button = QtWidgets.QToolButton(self.menu_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/ui\\icon/min_window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_button.setIcon(icon1)
        self.min_button.setIconSize(QtCore.QSize(50, 50))
        self.min_button.setObjectName("min_button")
        self.horizontalLayout_6.addWidget(self.min_button)
        self.max_button = QtWidgets.QToolButton(self.menu_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("src/ui\\icon/open_in_full_window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_button.setIcon(icon2)
        self.max_button.setIconSize(QtCore.QSize(50, 50))
        self.max_button.setObjectName("max_button")
        self.horizontalLayout_6.addWidget(self.max_button)
        self.close_button = QtWidgets.QToolButton(self.menu_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("src/ui\\icon/close_window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon3)
        self.close_button.setIconSize(QtCore.QSize(50, 50))
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_6.addWidget(self.close_button)
        self.horizontalLayout_3.addWidget(self.menu_3)
        self.verticalLayout.addWidget(self.menu)
        self.main_window = QtWidgets.QWidget(self.teacher_mode)
        self.main_window.setObjectName("main_window")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_window)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.side_menu_2 = QtWidgets.QWidget(self.main_window)
        self.side_menu_2.setMinimumSize(QtCore.QSize(150, 0))
        self.side_menu_2.setMaximumSize(QtCore.QSize(1500, 16777215))
        self.side_menu_2.setStyleSheet("QPushButton{\n"
"border:none;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"border-radius:5px;\n"
"border-style:2px solid block;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:white;\n"
"border-radius:5px;\n"
"border-style:2px solid block;\n"
"}\n"
"QWidget{\n"
"background-color:#FFCD00;\n"
"}")
        self.side_menu_2.setObjectName("side_menu_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.side_menu_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.home_2_button = QtWidgets.QPushButton(self.side_menu_2)
        font = QtGui.QFont()
        font.setFamily("AniMe Matrix - MB_EN")
        font.setPointSize(10)
        self.home_2_button.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("src/ui\\icon/house.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_2_button.setIcon(icon4)
        self.home_2_button.setIconSize(QtCore.QSize(50, 50))
        self.home_2_button.setCheckable(True)
        self.home_2_button.setAutoExclusive(True)
        self.home_2_button.setObjectName("home_2_button")
        self.verticalLayout_3.addWidget(self.home_2_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem2)
        self.database_2_button = QtWidgets.QPushButton(self.side_menu_2)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.database_2_button.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("src/ui\\icon/contact_page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.database_2_button.setIcon(icon5)
        self.database_2_button.setIconSize(QtCore.QSize(50, 50))
        self.database_2_button.setCheckable(True)
        self.database_2_button.setAutoExclusive(True)
        self.database_2_button.setObjectName("database_2_button")
        self.verticalLayout_3.addWidget(self.database_2_button)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.analytics_2_button = QtWidgets.QPushButton(self.side_menu_2)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.analytics_2_button.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("src/ui\\icon/analytics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analytics_2_button.setIcon(icon6)
        self.analytics_2_button.setIconSize(QtCore.QSize(50, 50))
        self.analytics_2_button.setCheckable(True)
        self.analytics_2_button.setAutoExclusive(True)
        self.analytics_2_button.setObjectName("analytics_2_button")
        self.verticalLayout_3.addWidget(self.analytics_2_button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem4)
        self.setting_2_button = QtWidgets.QPushButton(self.side_menu_2)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.setting_2_button.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("src/ui\\icon/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_2_button.setIcon(icon7)
        self.setting_2_button.setIconSize(QtCore.QSize(50, 50))
        self.setting_2_button.setCheckable(True)
        self.setting_2_button.setAutoExclusive(True)
        self.setting_2_button.setObjectName("setting_2_button")
        self.verticalLayout_3.addWidget(self.setting_2_button)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem5)
        self.release_2_button = QtWidgets.QPushButton(self.side_menu_2)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.release_2_button.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("src/ui\\icon/new_releases.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.release_2_button.setIcon(icon8)
        self.release_2_button.setIconSize(QtCore.QSize(50, 50))
        self.release_2_button.setCheckable(True)
        self.release_2_button.setAutoExclusive(True)
        self.release_2_button.setObjectName("release_2_button")
        self.verticalLayout_3.addWidget(self.release_2_button)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_2.addWidget(self.side_menu_2)
        self.page_main = QtWidgets.QWidget(self.main_window)
        self.page_main.setObjectName("page_main")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_main)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stack_change_page = QtWidgets.QStackedWidget(self.page_main)
        self.stack_change_page.setMinimumSize(QtCore.QSize(30, 0))
        self.stack_change_page.setObjectName("stack_change_page")
        self.page_database = QtWidgets.QWidget()
        self.page_database.setObjectName("page_database")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_database)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget = QtWidgets.QWidget(self.page_database)
        self.widget.setMinimumSize(QtCore.QSize(900, 0))
        self.widget.setStyleSheet("QComboBox{\n"
"border:1px solid gray;\n"
"border-radius:6px;\n"
"padding:1px 18px 1px 3px;\n"
"background-color:black;\n"
"color:white;\n"
"selection-background-color:black;\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"border:2px solid gray;\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_9.setSpacing(20)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_push_create_stu = QtWidgets.QPushButton(self.widget)
        self.btn_push_create_stu.setMinimumSize(QtCore.QSize(160, 40))
        self.btn_push_create_stu.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_push_create_stu.setFont(font)
        self.btn_push_create_stu.setStyleSheet("#btn_push_create_stu{\n"
"border:none;\n"
"border-radius :6px;\n"
"background-color: #3795BD;\n"
"color:white;\n"
"}\n"
"\n"
"#btn_push_create_stu:hover{\n"
"border:none;\n"
"border-radius :6px;\n"
"background-color: #3A6D8C;\n"
"\n"
"color:white;\n"
"}\n"
"\n"
"#btn_push_create_stu:check{\n"
"border:none;\n"
"border-radius :6px;\n"
"background-color: #3A6D8C;\n"
"\n"
"color:white;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("src/ui\\icon/person_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_push_create_stu.setIcon(icon9)
        self.btn_push_create_stu.setIconSize(QtCore.QSize(30, 30))
        self.btn_push_create_stu.setCheckable(True)
        self.btn_push_create_stu.setAutoExclusive(True)
        self.btn_push_create_stu.setObjectName("btn_push_create_stu")
        self.horizontalLayout_9.addWidget(self.btn_push_create_stu)
        self.btn_import_excel = QtWidgets.QPushButton(self.widget)
        self.btn_import_excel.setMinimumSize(QtCore.QSize(160, 40))
        self.btn_import_excel.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_import_excel.setFont(font)
        self.btn_import_excel.setStyleSheet("#btn_import_excel{\n"
"border:none;\n"
"border-radius :6px;\n"
"background-color: #629584;\n"
"color:white;\n"
"}\n"
"\n"
"#btn_import_excel:hover{\n"
"border:none;\n"
"border-radius :6px;\n"
"background-color:#387478;\n"
"color:white;\n"
"}\n"
"\n"
"#btn_import_excel:check{\n"
"border:none;\n"
"border-radius :6px;\n"
"background-color:#387478;\n"
"color:white;\n"
"\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("src/ui\\icon/import_excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_import_excel.setIcon(icon10)
        self.btn_import_excel.setIconSize(QtCore.QSize(30, 30))
        self.btn_import_excel.setObjectName("btn_import_excel")
        self.horizontalLayout_9.addWidget(self.btn_import_excel)
        self.btn_import_qrcode = QtWidgets.QPushButton(self.widget)
        self.btn_import_qrcode.setMinimumSize(QtCore.QSize(160, 40))
        self.btn_import_qrcode.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_import_qrcode.setFont(font)
        self.btn_import_qrcode.setStyleSheet("#btn_import_qrcode{\n"
"border:none;\n"
"border-radius :6px;\n"
"background-color:gray;\n"
"color:white;\n"
"}\n"
"\n"
"#btn_import_qrcode:hover{\n"
"border:none;\n"
"border-radius :6px;\n"
"background-color: black;\n"
"color:white;\n"
"}\n"
"\n"
"#btn_import_qrcode:check{\n"
"border:none;\n"
"border-radius :6px;\n"
"background-color:black;\n"
"color: white;\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("src/ui\\icon/import_qr_code.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_import_qrcode.setIcon(icon11)
        self.btn_import_qrcode.setIconSize(QtCore.QSize(30, 30))
        self.btn_import_qrcode.setObjectName("btn_import_qrcode")
        self.horizontalLayout_9.addWidget(self.btn_import_qrcode)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_12.setSpacing(20)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.box_search_class = QtWidgets.QComboBox(self.widget)
        self.box_search_class.setMinimumSize(QtCore.QSize(160, 30))
        self.box_search_class.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.box_search_class.setFont(font)
        self.box_search_class.setObjectName("box_search_class")
        self.horizontalLayout_12.addWidget(self.box_search_class)
        self.btn_filter = QtWidgets.QToolButton(self.widget)
        self.btn_filter.setStyleSheet("\n"
"QToolButton {\n"
"    border: none; /* 去掉邊框 */\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("src/ui\\icon/filter_alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_filter.setIcon(icon12)
        self.btn_filter.setIconSize(QtCore.QSize(30, 30))
        self.btn_filter.setObjectName("btn_filter")
        self.horizontalLayout_12.addWidget(self.btn_filter)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.txt_search_stu = QtWidgets.QLineEdit(self.widget)
        self.txt_search_stu.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_search_stu.setMaximumSize(QtCore.QSize(500, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.txt_search_stu.setFont(font)
        self.txt_search_stu.setObjectName("txt_search_stu")
        self.horizontalLayout_12.addWidget(self.txt_search_stu)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.table_stu = QtWidgets.QTableWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.table_stu.setFont(font)
        self.table_stu.setStyleSheet("QHeaderView::section{\n"
"font-weight: bold;\n"
"background-color: black;\n"
"color:white;\n"
"}\n"
"\n"
"QTableWidget{\n"
"alternate-background-color: #D8D9DA;\n"
"background-color:#FCFAED;\n"
"}")
        self.table_stu.setAlternatingRowColors(True)
        self.table_stu.setObjectName("table_stu")
        self.table_stu.setColumnCount(6)
        self.table_stu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_stu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stu.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stu.setHorizontalHeaderItem(5, item)
        self.verticalLayout_5.addWidget(self.table_stu)
        self.horizontalLayout_8.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.page_database)
        self.widget_2.setMinimumSize(QtCore.QSize(250, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.stack_create_data = QtWidgets.QStackedWidget(self.widget_2)
        self.stack_create_data.setStyleSheet("\n"
"QToolButton {\n"
"    border: none; /* 去掉邊框 */\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: #FFCD00; /* 選中時的背景顏色 */\n"
"    border-radius: 5px; /* 圓角邊框 */\n"
"    border: 3px solid #FFCD00; /* 邊框樣式：2px 寬的黑色實線 */\n"
"}\n"
"\n"
"QToolButton:checked {\n"
"    background-color:#FFCD00; /* 選中時的背景顏色 */\n"
"    border-radius: 5px; /* 圓角邊框 */\n"
"    border: 3px solid #FFCD00; /* 邊框樣式：2px 寬的黑色實線 */\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"    border-bottom:1px solid black;\n"
"}\n"
"")
        self.stack_create_data.setObjectName("stack_create_data")
        self.page_create_new_data = QtWidgets.QWidget()
        self.page_create_new_data.setObjectName("page_create_new_data")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_create_new_data)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.icon_create_data = QtWidgets.QLabel(self.page_create_new_data)
        self.icon_create_data.setText("")
        self.icon_create_data.setPixmap(QtGui.QPixmap("src/ui\\icon/account.png"))
        self.icon_create_data.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_create_data.setObjectName("icon_create_data")
        self.verticalLayout_7.addWidget(self.icon_create_data)
        self.txt_create_data = QtWidgets.QLabel(self.page_create_new_data)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.txt_create_data.setFont(font)
        self.txt_create_data.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_create_data.setObjectName("txt_create_data")
        self.verticalLayout_7.addWidget(self.txt_create_data)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem10)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_4.setSpacing(25)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.input_sex = QtWidgets.QComboBox(self.page_create_new_data)
        self.input_sex.setMinimumSize(QtCore.QSize(180, 30))
        self.input_sex.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.input_sex.setFont(font)
        self.input_sex.setObjectName("input_sex")
        self.input_sex.addItem("")
        self.input_sex.addItem("")
        self.verticalLayout_4.addWidget(self.input_sex)
        self.input_class = QtWidgets.QLineEdit(self.page_create_new_data)
        self.input_class.setMinimumSize(QtCore.QSize(180, 30))
        self.input_class.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.input_class.setFont(font)
        self.input_class.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_class.setObjectName("input_class")
        self.verticalLayout_4.addWidget(self.input_class)
        self.input_seat_number = QtWidgets.QLineEdit(self.page_create_new_data)
        self.input_seat_number.setMinimumSize(QtCore.QSize(180, 30))
        self.input_seat_number.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.input_seat_number.setFont(font)
        self.input_seat_number.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_seat_number.setObjectName("input_seat_number")
        self.verticalLayout_4.addWidget(self.input_seat_number)
        self.input_name = QtWidgets.QLineEdit(self.page_create_new_data)
        self.input_name.setMinimumSize(QtCore.QSize(180, 30))
        self.input_name.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.input_name.setFont(font)
        self.input_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_name.setObjectName("input_name")
        self.verticalLayout_4.addWidget(self.input_name)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem11)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_trash = QtWidgets.QToolButton(self.page_create_new_data)
        self.btn_trash.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("src/ui\\icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_trash.setIcon(icon13)
        self.btn_trash.setIconSize(QtCore.QSize(35, 35))
        self.btn_trash.setObjectName("btn_trash")
        self.horizontalLayout_11.addWidget(self.btn_trash)
        spacerItem12 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.btn_save = QtWidgets.QToolButton(self.page_create_new_data)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("src/ui\\icon/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon14)
        self.btn_save.setIconSize(QtCore.QSize(35, 35))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_11.addWidget(self.btn_save)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        spacerItem13 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem13)
        self.btn_create_file = QtWidgets.QPushButton(self.page_create_new_data)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.btn_create_file.setFont(font)
        self.btn_create_file.setObjectName("btn_create_file")
        self.verticalLayout_7.addWidget(self.btn_create_file)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem14)
        self.stack_create_data.addWidget(self.page_create_new_data)
        self.page_create_new_file = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("AniMe Matrix - MB_EN")
        font.setPointSize(14)
        self.page_create_new_file.setFont(font)
        self.page_create_new_file.setObjectName("page_create_new_file")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_create_new_file)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.icon_create_file = QtWidgets.QLabel(self.page_create_new_file)
        self.icon_create_file.setText("")
        self.icon_create_file.setPixmap(QtGui.QPixmap("src/ui\\icon/edit.png"))
        self.icon_create_file.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_create_file.setObjectName("icon_create_file")
        self.verticalLayout_8.addWidget(self.icon_create_file)
        self.txt_create_file = QtWidgets.QLabel(self.page_create_new_file)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.txt_create_file.setFont(font)
        self.txt_create_file.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_create_file.setObjectName("txt_create_file")
        self.verticalLayout_8.addWidget(self.txt_create_file)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem15)
        self.btn_download_file = QtWidgets.QPushButton(self.page_create_new_file)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.btn_download_file.setFont(font)
        self.btn_download_file.setObjectName("btn_download_file")
        self.verticalLayout_8.addWidget(self.btn_download_file)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem16)
        self.btn_import_csvfile = QtWidgets.QPushButton(self.page_create_new_file)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.btn_import_csvfile.setFont(font)
        self.btn_import_csvfile.setObjectName("btn_import_csvfile")
        self.verticalLayout_8.addWidget(self.btn_import_csvfile)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem17)
        self.btn_create_data = QtWidgets.QPushButton(self.page_create_new_file)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.btn_create_data.setFont(font)
        self.btn_create_data.setObjectName("btn_create_data")
        self.verticalLayout_8.addWidget(self.btn_create_data)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem18)
        self.stack_create_data.addWidget(self.page_create_new_file)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stack_create_data.addWidget(self.page)
        self.horizontalLayout_10.addWidget(self.stack_create_data)
        self.horizontalLayout_8.addWidget(self.widget_2)
        self.stack_change_page.addWidget(self.page_database)
        self.page_analytic = QtWidgets.QWidget()
        self.page_analytic.setObjectName("page_analytic")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_analytic)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page_analytic)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.stack_change_page.addWidget(self.page_analytic)
        self.page_setting = QtWidgets.QWidget()
        self.page_setting.setObjectName("page_setting")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_setting)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page_setting)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.stack_change_page.addWidget(self.page_setting)
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_home)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.page_home)
        font = QtGui.QFont()
        font.setFamily("AniMe Matrix - MB_EN")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.stack_change_page.addWidget(self.page_home)
        self.page_release = QtWidgets.QWidget()
        self.page_release.setObjectName("page_release")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_release)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.page_release)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.stack_change_page.addWidget(self.page_release)
        self.horizontalLayout_5.addWidget(self.stack_change_page)
        self.horizontalLayout_2.addWidget(self.page_main)
        self.verticalLayout.addWidget(self.main_window)
        self.horizontalLayout.addWidget(self.teacher_mode)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stack_change_page.setCurrentIndex(0)
        self.stack_create_data.setCurrentIndex(0)
        self.open_menu_button.toggled['bool'].connect(self.side_menu_2.setHidden) # type: ignore
        self.btn_push_create_stu.toggled['bool'].connect(self.widget_2.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.teacher_txt.setText(_translate("MainWindow", "教師模式"))
        self.min_button.setText(_translate("MainWindow", "..."))
        self.max_button.setText(_translate("MainWindow", "..."))
        self.close_button.setText(_translate("MainWindow", "..."))
        self.home_2_button.setText(_translate("MainWindow", "首頁"))
        self.database_2_button.setText(_translate("MainWindow", "資料管理"))
        self.analytics_2_button.setText(_translate("MainWindow", "學習分析"))
        self.setting_2_button.setText(_translate("MainWindow", "設定細節"))
        self.release_2_button.setText(_translate("MainWindow", "版本更新"))
        self.label.setText(_translate("MainWindow", " 學生資料"))
        self.btn_push_create_stu.setText(_translate("MainWindow", "新增學生"))
        self.btn_import_excel.setText(_translate("MainWindow", "匯出Excel"))
        self.btn_import_qrcode.setText(_translate("MainWindow", "匯出QRcode"))
        self.btn_filter.setText(_translate("MainWindow", "..."))
        self.txt_search_stu.setPlaceholderText(_translate("MainWindow", "搜尋學生"))
        item = self.table_stu.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "班級"))
        item = self.table_stu.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "性別"))
        item = self.table_stu.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "座號"))
        item = self.table_stu.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.table_stu.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "下載個人QRcode"))
        item = self.table_stu.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "刪除"))
        self.txt_create_data.setText(_translate("MainWindow", "新增單筆學生資料"))
        self.input_sex.setItemText(0, _translate("MainWindow", "男孩"))
        self.input_sex.setItemText(1, _translate("MainWindow", "女孩"))
        self.input_class.setPlaceholderText(_translate("MainWindow", "學生班級"))
        self.input_seat_number.setPlaceholderText(_translate("MainWindow", "學生座號"))
        self.input_name.setPlaceholderText(_translate("MainWindow", "學生姓名"))
        self.btn_save.setText(_translate("MainWindow", "..."))
        self.btn_create_file.setText(_translate("MainWindow", "新增批量資料"))
        self.txt_create_file.setText(_translate("MainWindow", "批量新增學生資料"))
        self.btn_download_file.setText(_translate("MainWindow", "下載匯入範本"))
        self.btn_import_csvfile.setText(_translate("MainWindow", "匯入csv檔"))
        self.btn_create_data.setText(_translate("MainWindow", "新增單筆資料"))
        self.label_2.setText(_translate("MainWindow", "學習分析"))
        self.label_3.setText(_translate("MainWindow", "設定細節"))
        self.label_5.setText(_translate("MainWindow", "home Page"))
        self.label_4.setText(_translate("MainWindow", "版本更新"))
